"""Added youtube_video_path in short_video table

Revision ID: 2ed46c0ef6db
Revises: ef7b2f82ca3d
Create Date: 2026-06-15 14:53:53.602410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ed46c0ef6db'
down_revision: Union[str, Sequence[str], None] = 'ef7b2f82ca3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contents', 'merged_path')
    op.add_column('short_videos', sa.Column('youtube_video_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('short_videos', 'youtube_video_path')
    op.add_column('contents', sa.Column('merged_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
