"""Added shot_video table

Revision ID: cf7bb67201db
Revises: ccd058256b6e
Create Date: 2026-06-12 18:41:28.198858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf7bb67201db'
down_revision: Union[str, Sequence[str], None] = 'ccd058256b6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('short_videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('output_path', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('NOT_STARTED', 'PROCESSING', 'COMPLETED', 'PUBLISHED', 'FAILED', name='shortvideostatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_short_videos_id'), 'short_videos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_short_videos_id'), table_name='short_videos')
    op.drop_table('short_videos')
    # ### end Alembic commands ###
