"""added new columns in short video table

Revision ID: ef7b2f82ca3d
Revises: cf7bb67201db
Create Date: 2026-06-15 12:53:10.387223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef7b2f82ca3d'
down_revision: Union[str, Sequence[str], None] = 'cf7bb67201db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('short_videos', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('short_videos', sa.Column('tags', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('short_videos', 'tags')
    op.drop_column('short_videos', 'description')
    # ### end Alembic commands ###
